application:
  debian_packages:
    - python3-venv
    - jq
    - curl
  python_deps:
    fsm:
      - daemonize~=2.5
      - flask~=3.0
      - requests~=2.32
    scs:
      - daemonize~=2.5
      - flask~=3.0
      - requests~=2.32
